### ISSUE TITLE
How to get C++17 supported tool chain? 

### ISSUE THREAD

**Issue by mbandu** [platformio/platform-titiva#15]
Hi,

How to do C++17 support tool chain?
I am trying to target Tiva.. arm-none-eabi-g++ doesn't seem to support C++14 or C++17.

Regards,

Bandu

**Comment by valeros** [comment]
Hi @mbandu ! Try to override the default toolchain package in your `platformio.ini` file:
```ini
; Use updated version of the GCC toolchain v9.2.1
platform_packages =
  toolchain-gccarmnoneeabi@~1.90201.0
```

**Comment by vortex314** [comment]
Why is the latest package not the default ? As I also looked to have a more recent compiler.
