### ISSUE TITLE
Unable to debug on TI TM4C123 platform / Windows

### ISSUE THREAD

**Issue by geojitsu** [platformio/platform-titiva#4]
OpenOCD unable to connect error when attempting to debug.

[Platform IO Thread with details.](https://community.platformio.org/t/unable-to-debug-on-tm4c123-platform-windows/7208/19)

Ivan's the best

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-titiva/releases/tag/v2.0.7

Please update dev/platform.

**Comment by geojitsu** [comment]
So far so good.  For all the hard work you just got yourself a new customer.  Can't thank you enough.

**Comment by ivankravets** [comment]
Does it work now? :)

**Comment by geojitsu** [comment]
It does, you guys rule. This will make developing much less painful.  Keil may be a bit quicker in the hardware response time domain, but as an IDE, I'm sorry it's so antiquated.
