### ISSUE TITLE
Launchxl-cc1310 Support

### ISSUE THREAD

**Issue by thejobbitt** [platformio/platform-titiva#5]
[launchxl-CC1310](http://www.ti.com/tool/LAUNCHXL-CC1310?keyMatch=launch%20cc1310&tisearch=Search-EN-Everything) Info

**Comment by nanosonde** [comment]
Would this be ok as a starting point? It was taken from the TivaC platform.

https://github.com/nanosonde/platform-ticc13x0
https://github.com/nanosonde/platformio-packages

**Comment by thejobbitt** [comment]
Being over a year ago, I had forgotten I made the request. The project I needed this for is long over, I'm sure this will help future designers that want to use this development board. Thanks!
