### ISSUE TITLE
tool-openocd not being installed for upload

### ISSUE THREAD

**Issue by pfeerick** [platformio/platform-titiva#6]
This package is not being automatically installed (when not present) when trying to upload to the TI LaunchPad (Tiva C) w/ tm4c123 (80MHz) - lptm4c1230c3pm - hence causing the upload to fail. 

https://github.com/platformio/platform-titiva/blob/a02b171b3b04eac8ab04b71431a2489f5d4edce0/platform.json#L45-L49

with `platformio.ini` consisting of 

```
[env:lptm4c1230c3pm]
platform = titiva
board = lptm4c1230c3pm
framework = energia
```

openocd is found after running `platformio platform install titiva --with-package tool-openocd`

Applies to stable and beta.

Forum reference: https://community.platformio.org/t/ti-launchpad-tiva-c-upload-error/8407

**Comment by ivankravets** [comment]
Thanks! Please update to https://github.com/platformio/platform-titiva/releases/tag/v2.0.8
